/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-08 06:28:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class yongsign_005fx_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

//2020_01_02 수정부분
	String url = request.getServletPath();
	session.setAttribute("url",url);
	String includeurl = "header.jsp";
	String uss = (String)session.getAttribute("id");
	String log = "로그인";
	if(uss==null)
		uss="GUEST";
	 else{
	 	log="로그아웃";
		includeurl = "sign_login.jsp";
	 }
		//수정부분 끝

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("  <meta name=\"Author\" content=\"\">\r\n");
      out.write("  <meta name=\"Keywords\" content=\"\">\r\n");
      out.write("  <meta name=\"Description\" content=\"\">\r\n");
      out.write("  <title>sign</title>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/datepicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/common/form_check.js\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css\\join.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/classic.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/classic.date.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/classic.time.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("\t<!----------------------------메인 스타일-------------------------->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/yongsign_x_materialFormStyles.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("\t<script src=\"js/materialForm.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--2020.01.03 추가 css 분리-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/logform.css\" media=\"screen\">\r\n");
      out.write("<!--2020.01.03 추가 javascript.가입기능 분리-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/signjs.js\"></script>\r\n");
      out.write("\t<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("\t<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("\t<script type='text/javascript'>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t  $('#forgot_username_link').tipsy({gravity: 'w'});   \r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".signin\").click(function(e) {          \r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\t\t\treturn false\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(e.target).parent(\"a.signin\").length==0) {\r\n");
      out.write("\t\t\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t var shrinkHeader = 30;\r\n");
      out.write("\t\t var shrinkhollow = 465;\r\n");
      out.write("\t\t  $(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\t  if ( scroll >= shrinkHeader ) {\r\n");
      out.write("\t\t\t\t   $('#navtop').addClass('shrink');  \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$('#navtop').removeClass('shrink');\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t   if(scroll>= shrinkhollow ){\r\n");
      out.write("\t\t\t\t\t$('#navtop').addClass('shrinkhollow');  \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$('#navtop').removeClass('shrinkhollow');\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction getCurrentScroll() {\r\n");
      out.write("\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- -----------------다음 주소 api ----------------------------------------->\r\n");
      out.write("\t<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write(" </head>\r\n");
      out.write(" <body>\r\n");
      out.write(" \t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\t\t\t\t<div class=\"container\" id=\"formOutterWrapper\">\r\n");
      out.write("<h1>그린풋살파크 용병가입</h1>\r\n");
      out.write("        <div class=\"container\" id=\"formInnerWrapper\">\r\n");
      out.write("                <form name = \"join\" id=\"materialForm\" class=\"form\" method=\"post\" action=\"signInsert.jsp\" role=\"form\" autocomplete=\"off\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"col-xs-2\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-8\">\r\n");
      out.write("                            <label class=\"labels\" for=\"id\">용병이름</label>\r\n");
      out.write("                            <input type=\"text\" class=\"formInput\" id=\"id\" name=\"id\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xs-2\">\r\n");
      out.write("                            <label class=\"labels\" for=\"hp1\">휴대폰번호</label>\r\n");
      out.write("                            <input type=\"text\" class=\"formInput\" id=\"hp1\" name=\"hp1\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"position:relative; top:-17px; right:-25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>-</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("                            <label class=\"labels\" for=\"hp2\"></label>\r\n");
      out.write("                            <input type=\"text\" class=\"formInput\" id=\"hp2\" name=\"hp2\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"position:relative; top:-17px; right:-25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>-</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("                            <label class=\"labels\" for=\"hp3\"></label>\r\n");
      out.write("                            <input type=\"text\" class=\"formInput\" id=\"hp3\" name=\"hp3\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t지점\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lv\"  class = formInput><option value=\"2\">2지점<option value=\"1\">1지점</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t구장\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lv\"  class = formInput><option value=\"2\">2구장<option value=\"1\">1구장</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t실력\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lv\"  class = formInput><option value=\"5\">상<option value=\"4\">중상<option value=\"3\">중<option value=\"2\">중하<option value=\"1\">하</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("                            성별\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type =\"radio\" name=\"gender\" value=\"female\" checked>여성\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type =\"radio\" name=\"gender\" value=\"male\">남성\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t매치일정\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lv\"  class = formInput><option value=\"3\">주말<option value=\"2\">주중<option value=\"1\">별도문의</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t시간선택\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lv\"  class = formInput><option value=\"3\">오후<option value=\"2\">오전<option value=\"1\">별도문의</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t소속팀존재유무\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-6 radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"team\" id=\"team\" value=\"teamok\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t있음\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"team\" id=\"team\" value=\"teamno\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t없음\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t선호포지션\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-8 checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=hobby value=\"FW\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFW\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=hobby value=\"MF\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMF\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=hobby value=\"DF\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tDF\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" name=hobby value=\"GK\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tGK\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-2\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:16px; font-weight:400;\">\r\n");
      out.write("\t\t\t\t\t\t\t마감여부\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lv\"  class = formInput><option value=\"2\">가능<option value=\"1\">마감</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-8\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                        <div class=\"col-xs-1\">\r\n");
      out.write("                            <input type =\"button\" value = \"가입\" class=\"btn btn-primary\" onClick=\"joinsubmit()\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("                        </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:14px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type = \"reset\" value=\"초기화\" class=\"btn btn-danger\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"hidden\" value=\"\" />\r\n");
      out.write("                </form>\r\n");
      out.write("        </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-2.2.3.min.js\" integrity=\"sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=\"   crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"js/materialForm.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
