/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-01-09 02:37:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class yongsign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//2020_01_02 수정부분
	String includeurl = "header.jsp";
	String uss = (String) session.getAttribute("id");
	String log = "로그인";
	if (uss == null)
		uss = "GUEST";
	else {
		log = "로그아웃";
		includeurl = "sign_login.jsp";
	}
	//수정부분 끝

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"Generator\" content=\"EditPlus®\">\r\n");
      out.write("<meta name=\"Author\" content=\"\">\r\n");
      out.write("<meta name=\"Keywords\" content=\"\">\r\n");
      out.write("<meta name=\"Description\" content=\"\">\r\n");
      out.write("<title>yongsign</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/datepicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/common/form_check.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css\\join.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.date.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signbutton.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/signformrelocation.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/classic.time.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style2.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/materialFormStyles2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/borderRightLeft.css\" media=\"screen\">\r\n");
      out.write("<script src=\"js/materialForm.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--기본적인 body등의 css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/basicStyle.css\" media=\"screen\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navmid33.css\">\r\n");
      out.write("\t<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.infinitecarousel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--2020.01.03 추가 css 분리-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/logform.css\" media=\"screen\">\r\n");
      out.write("\t<!--2020.01.03 추가 javascript.가입기능 분리-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/signjs.js\"></script>\r\n");
      out.write("<!----------------------------alam form 추가 2020.01.06-------------------------->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t$(\".mypage\").click(function(e) {          \r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t$(\"fieldset#mypage_menu\").toggle();\r\n");
      out.write("\t\t\t\t\t$(\".mypage\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t});\t\t\r\n");
      out.write("\t\t\t\t$(\"fieldset#mypage_menu\").mouseup(function() {\r\n");
      out.write("\t\t\t\t\treturn false\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(e.target).parent(\"a.mypage\").length!=0) {\r\n");
      out.write("\t\t\t\t\t\t$(\".mypage\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t\t\t$(\"fieldset#mypage_menu\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<!----------------------------서브메뉴마우스오버기능-------------------------->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/subMenuMouseOver.css\">\r\n");
      out.write("\t<!----------------------------회원가입스크립트랑 스타일(따로 빼면 에러)-------------------------->\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t  $('#forgot_username_link').tipsy({gravity: 'w'});   \r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<link href=\"css/front.css\" media=\"screen, projection\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\".signin\").click(function(e) {          \r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t$(\"fieldset#signin_menu\").toggle();\r\n");
      out.write("\t\t\t\t\t$(\".signin\").toggleClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"fieldset#signin_menu\").mouseup(function() {\r\n");
      out.write("\t\t\t\t\treturn false\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(document).mouseup(function(e) {\r\n");
      out.write("\t\t\t\t\tif($(e.target).parent(\"a.signin\").length==0) {\r\n");
      out.write("\t\t\t\t\t\t$(\".signin\").removeClass(\"menu-open\");\r\n");
      out.write("\t\t\t\t\t\t$(\"fieldset#signin_menu\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!----------------------------회원가입스크립트랑 스타일여기까지------------------------------------>\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t var shrinkHeader = 30;\r\n");
      out.write("\t\t var shrinkhollow = 465;\r\n");
      out.write("\t\t  $(window).scroll(function() {\r\n");
      out.write("\t\t\tvar scroll = getCurrentScroll();\r\n");
      out.write("\t\t\t  if ( scroll >= shrinkHeader ) {\r\n");
      out.write("\t\t\t\t   $('#navtop').addClass('shrink');  \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$('#navtop').removeClass('shrink');\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t   if(scroll>= shrinkhollow ){\r\n");
      out.write("\t\t\t\t\t$('#navtop').addClass('shrinkhollow');  \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse {\r\n");
      out.write("\t\t\t\t\t$('#navtop').removeClass('shrinkhollow');\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction getCurrentScroll() {\r\n");
      out.write("\t\treturn window.pageYOffset || document.documentElement.scrollTop;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<!-- -----------------다음 주소 api ----------------------------------------->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<!-- ------------------------------------------------------------------------- -->\r\n");
      out.write("<!-- -------------------------ID 중복확인에 대한 ajax--------------------------------- -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#id\").blur(function(){\r\n");
      out.write("\t\t\tvar idReg = /^[a-zA-z]+[a-zA-z0-9]{5,13}$/g;\r\n");
      out.write("\t\t\tif(idReg.test(join.id.value))\r\n");
      out.write("\t\t\t\tcallAjax();\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#ajaxReturn\").html(\"6~14자 사이의 영문 대소문자와 숫자만 사용가능합니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#name\").blur(function(){\r\n");
      out.write("\t\t\tif(join.name.value.length!=0)\r\n");
      out.write("\t\t\t\t$(\"#nameReturn\").html(\"\");\r\n");
      out.write("\t\t\telse{     \r\n");
      out.write("\t\t\t\t$(\"#nameReturn\").html(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#hp2\").blur(function(){\r\n");
      out.write("\t\t\tif(join.hp2.value.length!=0)\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"\");\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"휴대폰번호를 입력하세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#hp3\").blur(function(){\r\n");
      out.write("\t\t\tif(join.hp3.value.length!=0)\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"\");\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#hpReturn\").html(\"휴대폰번호를 입력하세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#em1\").blur(function(){\r\n");
      out.write("\t\t\tif(join.em1.value.length!=0)\r\n");
      out.write("\t\t\t\t$(\"#emReturn\").html(\"\");\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#emReturn\").html(\"이메일을 입력하세요.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction callAjax(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\turl:\"./confirmId.jsp\",       \r\n");
      out.write("\t\tdata:{\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tid:$('#id').val()\r\n");
      out.write("\t\t},\t\r\n");
      out.write("\t\tsuccess:whenSuccess,\r\n");
      out.write("\t\terror:whenError\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tvar confirmid = \"\";\r\n");
      out.write("\tfunction whenSuccess(resdata){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar x=document.getElementById(\"ajaxReturn\");\r\n");
      out.write("\t\t$(\"#ajaxReturn\").html(resdata);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(resdata.includes(\"이미 사용중인 ID입니다\")){\r\n");
      out.write("\t\t\tdocument.join.hidden.value=\"0\";\r\n");
      out.write("\t\t\tx.style.color=\"red\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tdocument.join.hidden.value=\"1\";\r\n");
      out.write("\t\t\tx.style.color=\"blue\";\r\n");
      out.write("\t\t\tconfirmid = join.id.value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction whenError(){\r\n");
      out.write("\t\talert(\"Error\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 비밀번호 체크 ajax -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function callAjax2(){\r\n");
      out.write("\tif(join.pw.value!=join.pwch.value){\r\n");
      out.write("\t\t$(\"#pwReturn\").html(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#pwReturn\").html(\"\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, includeurl, out, false);
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"mainleft\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"leftbanner\">\r\n");
      out.write("\t\t\t<div id=\"banner1\">\r\n");
      out.write("\t\t\t\t<img src=\"img/20191211.jpg\" width=\"100%\" height=\"100%\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"banner3\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d25325.265446899888!2d127.02924799651784!3d37.492391917303266!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357ca5bed583f92d%3A0xc93c837d2875ade6!2z7ZKL7IK07J6l!5e0!3m2!1sko!2skr!4v1575961834128!5m2!1sko!2skr\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border: 0;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"mainright\">\r\n");
      out.write("\t\t\t<div id=\"matList\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"container\" id=\"formOutterWrapper\">\r\n");
      out.write("\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t<h2>용병 등록</h2>\r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t<div class=\"container\" id=\"formInnerWrapper\">\r\n");
      out.write("\t\t\t\t\t\t<form name=\"yongjoin\" id=\"materialForm\" class=\"form\" method=\"post\" action=\"yongsignInsert.jsp\" role=\"form\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"yBranch\" class=formInput>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">지점선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>동대문점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>안산 고진점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>서수원점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>일산점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>대전 탄방점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>동대전점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>부산 가야점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>울산 남구점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>창원점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>전주 완산점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>울산 북구점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>GLOBAL ARENA(Japan)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>부산 북구점</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>Seogwipo. JEJU</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>가천대학교 운동장</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"yGround\" class=formInput>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">구장선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>A구장</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>B구장</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>C구장</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"yMember\">신청자명</label> <input type=\"text\" class=\"formInput\" id=\"yMember\" name=\"yMember\" style=\"font-size:18px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"\">연락처</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"formInput\" id=\"yTel1\" name=\"yTel1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>018</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">-</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"yTel2\"></label> <input type=\"text\" class=\"formInput\" id=\"yTel2\" name=\"yTel2\" style=\"font-size:18px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">-</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"yTel3\"></label> <input type=\"text\" class=\"formInput\" id=\"yTel3\" name=\"yTel3\" style=\"font-size:18px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-1\" style=\"font-size:18px; width:120px; letter-spacing:4px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t매치일정\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"formInput\" id=\"yMatchdate\" name=\"yMatchdate\" style=\"font-size:18px; width:200px;\" placeholder=\"ex)2020-08-20\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\" style=\"margin-left:-25px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select class=\"formInput\" id=\"yTime\" name=\"yTime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">시간선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>1시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>2시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"yApply\" id=\"yApply\" class=formInput>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">마감여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>가능</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>마감</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"yTeam\" id=\"yTeam\" class=formInput>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\">팀수준선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>중상</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>중</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>중하</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>하</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"height:284px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-2\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"labels\" for=\"yContents\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea name=\"yContents\" id=\"yContents\" style=\"width:730px;resize:none; height:200px;\" placeholder=\"메모를 입력하세요.\" ></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\" style=\"font-size: 14px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-4\" style=\"margin-left: 45px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"등록\" class=\"signbutton signbutton5\" onClick=\"yongjoinsubmit()\" style=\"font-size:18px; width:140px; letter-spacing:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" value=\"취소\" class=\"signbutton signbuttoncancel\" style=\"font-size:18px; width:140px; letter-spacing:5px;\" onClick=\"script: location.href='yonglist_1.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"hidden\" value=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script src=\"https://code.jquery.com/jquery-2.2.3.min.js\" integrity=\"sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"js/materialForm.js\"></script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer id=\"footer\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
